#ifndef SHRGRAPHICS_H
#define SHRGRAPHICS_H

// Controllers
//#include "ShrBlendTransformController.h"
//#include "ShrControlledObject.h"
//#include "ShrController.h"
//#include "ShrIKController.h"
//#include "ShrIKGoal.h"
//#include "ShrIKJoint.h"
//#include "ShrKeyframeController.h"
//#include "ShrMorphController.h"
//#include "ShrParticleController.h"
//#include "ShrPointController.h"
//#include "ShrSkinController.h"
//#include "ShrTransformController.h"

// CurvesSurfaces
//#include "ShrBoxSurface.h"
//#include "ShrBSplineSurfacePatch.h"
//#include "ShrCurveMesh.h"
//#include "ShrCurveSegment.h"
//#include "ShrFloatArray.h"
//#include "ShrFloat2Array.h"
//#include "ShrRectangleSurface.h"
//#include "ShrRevolutionSurface.h"
//#include "ShrSurfacePatch.h"
//#include "ShrSurfaceMesh.h"
//#include "ShrTubeSurface.h"

// DataTypes
//#include "ShrBound.h"
//#include "ShrColor.h"
//#include "ShrHalfFloat.h"
//#include "ShrSpecializedIO.h"
//#include "ShrTransform.h"
//#include "ShrUtility.h"

// Detail
//#include "ShrBillboardNode.h"
//#include "ShrClodMesh.h"
//#include "ShrCollapseRecord.h"
//#include "ShrCollapseRecordArray.h"
//#include "ShrCreateClodMesh.h"
//#include "ShrDlodNode.h"
//#include "ShrSwitchNode.h"

// GlobalEffects
//#include "ShrGlobalEffect.h"
//#include "ShrPlanarReflectionEffect.h"
//#include "ShrPlanarShadowEffect.h"

// Image Processing
//#include "ShrImageProcessing.h"
//#include "ShrImageProcessing2.h"
//#include "ShrImageProcessing3.h"

// LocalEffects
//#include "ShrDefaultEffect.h"
//#include "ShrLightAmbEffect.h"
//#include "ShrLightDirPerPixEffect.h"
//#include "ShrLightDirPerVerEffect.h"
//#include "ShrLightPntPerPixEffect.h"
//#include "ShrLightPntPerVerEffect.h"
//#include "ShrLightSptPerPixEffect.h"
//#include "ShrLightSptPerVerEffect.h"
//#include "ShrMaterialEffect.h"
//#include "ShrMaterialTextureEffect.h"
//#include "ShrTexture1DEffect.h"
//#include "ShrTexture2AddEffect.h"
//#include "ShrTexture2ColorBlendEffect.h"
//#include "ShrTexture2DEffect.h"
//#include "ShrTexture2MulEffect.h"
//#include "ShrTexture3DEffect.h"
//#include "ShrVertexColor3Effect.h"
//#include "ShrVertexColor4Effect.h"
//#include "ShrVertexColor4TextureEffect.h"

// Renderers
//#include "ShrRenderer.h"

#ifdef SHR_USE_OPENGL
//#include "ShrOpenGLBitmapFont.h"
//#include "ShrOpenGLIndexBuffer.h"
//#include "ShrOpenGLMapping.h"
//#include "ShrOpenGLPixelShader.h"
//#include "ShrOpenGLRendererData.h"
//#include "ShrOpenGLRenderTarget.h"
//#include "ShrOpenGLShader.h"
//#include "ShrOpenGLTexture1D.h"
//#include "ShrOpenGLTexture2D.h"
//#include "ShrOpenGLTexture3D.h"
//#include "ShrOpenGLTextureCube.h"
//#include "ShrOpenGLVertexBuffer.h"
//#include "ShrOpenGLVertexFormat.h"
//#include "ShrOpenGLVertexShader.h"
#endif

// Resources
//#include "ShrBuffer.h"
//#include "ShrIndexBuffer.h"
//#include "ShrRenderTarget.h"
//#include "ShrTexture.h"
//#include "ShrTexture1D.h"
//#include "ShrTexture2D.h"
//#include "ShrTexture3D.h"
//#include "ShrTextureCube.h"
//#include "ShrVertexBuffer.h"
//#include "ShrVertexBufferAccessor.h"
//#include "ShrVertexFormat.h"

// SceneGraph
//#include "ShrCamera.h"
//#include "ShrCameraNode.h"
//#include "ShrCuller.h"
//#include "ShrLight.h"
//#include "ShrLightNode.h"
//#include "ShrMaterial.h"
//#include "ShrNode.h"
//#include "ShrParticles.h"
//#include "ShrPicker.h"
//#include "ShrPickRecord.h"
//#include "ShrPolypoint.h"
//#include "ShrPolysegment.h"
//#include "ShrProjector.h"
//#include "ShrScreenTarget.h"
//#include "ShrSpatial.h"
//#include "ShrStandardMesh.h"
//#include "ShrTriangles.h"
//#include "ShrTriFan.h"
//#include "ShrTriMesh.h"
//#include "ShrTriStrip.h"
//#include "ShrVisibleSet.h"
//#include "ShrVisual.h"

// Shaders
//#include "ShrAlphaState.h"
//#include "ShrCullState.h"
//#include "ShrDepthState.h"
//#include "ShrOffsetState.h"
//#include "ShrPixelShader.h"
//#include "ShrShader.h"
//#include "ShrShaderParameters.h"
//#include "ShrStencilState.h"
//#include "ShrVertexShader.h"
//#include "ShrVisualEffect.h"
//#include "ShrVisualEffectInstance.h"
//#include "ShrVisualPass.h"
//#include "ShrVisualTechnique.h"
//#include "ShrWireState.h"

// ShaderFloats
//#include "ShrCameraModelDVectorConstant.h"
//#include "ShrCameraModelPositionConstant.h"
//#include "ShrCameraWorldDVectorConstant.h"
//#include "ShrCameraWorldPositionConstant.h"
//#include "ShrLightAmbientConstant.h"
//#include "ShrLightAttenuationConstant.h"
//#include "ShrLightDiffuseConstant.h"
//#include "ShrLightModelDVectorConstant.h"
//#include "ShrLightModelPositionConstant.h"
//#include "ShrLightSpecularConstant.h"
//#include "ShrLightSpotConstant.h"
//#include "ShrLightWorldDVectorConstant.h"
//#include "ShrLightWorldPositionConstant.h"
//#include "ShrMaterialAmbientConstant.h"
//#include "ShrMaterialDiffuseConstant.h"
//#include "ShrMaterialEmissiveConstant.h"
//#include "ShrMaterialSpecularConstant.h"
//#include "ShrPMatrixConstant.h"
//#include "ShrPVMatrixConstant.h"
//#include "ShrPVWMatrixConstant.h"
//#include "ShrProjectorMatrixConstant.h"
//#include "ShrProjectorWorldPositionConstant.h"
//#include "ShrShaderFloat.h"
//#include "ShrVMatrixConstant.h"
//#include "ShrVWMatrixConstant.h"
//#include "ShrWMatrixConstant.h"

// Sorting
//#include "ShrBspNode.h"
//#include "ShrConvexRegion.h"
//#include "ShrConvexRegionManager.h"
//#include "ShrCRMCuller.h"
//#include "ShrPortal.h"

// Terrain
//#include "ShrTerrainPage.h"
//#include "ShrTerrain.h"

#endif
